# Generated by Django 5.2.8 on 2025-11-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('ec', 'Electronics & Communication'), ('me', 'Mechanical Engineering'), ('sm', 'Smart Manufacturing')], max_length=10),
        ),
    ]
