# Generated by Django 5.2.8 on 2025-11-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_section_alter_studentprofile_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Professor Email',
                'verbose_name_plural': 'Professor Emails',
            },
        ),
    ]
