# Generated by Django 5.2.8 on 2025-11-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['batch_year', 'branch', 'section']},
        ),
        migrations.AddField(
            model_name='batch',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='batch',
            name='branch',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('ec', 'Electronics & Communication'), ('me', 'Mechanical Engineering'), ('sm', 'Smart Manufacturing')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_year', 'branch', 'section')},
        ),
    ]
